      PROGRAM MISSING2
      CHARACTER*80 INFILE,OUTFILE
      CHARACTER*1 HTAB,CH1
      INTEGER NUMIS(10),MISS(10),COUNT(100)
C
      CALL GETARG(1,INFILE)
      CALL GETARG(2,OUTFILE)
      HTAB=CHAR(9)
C
      OPEN(UNIT=1,FILE=INFILE,FORM='FORMATTED')
      REWIND(1)
      READ(1,'(A1)')(CH1,I=1,5)
      OPEN(UNIT=2,FILE=OUTFILE,FORM='FORMATTED')
      REWIND(2)
      WRITE(2,'(99A)') 'IS_10',HTAB,'MISS_10',HTAB,
     *'IS_20',HTAB,'MISS_20',HTAB,
     *'IS_30',HTAB,'MISS_30',HTAB,
     *'IS_40',HTAB,'MISS_40',HTAB,
     *'IS_50',HTAB,'MISS_50',HTAB,
     *'IS_60',HTAB,'MISS_60',HTAB,
     *'IS_70',HTAB,'MISS_70',HTAB,
     *'IS_80',HTAB,'MISS_80',HTAB,
     *'IS_90',HTAB,'MISS_90',HTAB,
     *'IS_100',HTAB,'MISS_100'
C
      DO 8 LUKE=1,10000
      DO 2 I=1,10
      NUMIS(I)=0
      MISS(I)=0
    2 CONTINUE
      READ(1,*)(COUNT(I),I=1,100)
      DO 6 ISET=1,10
      I2=10*ISET
      DO 4 I=1,I2
      NUMIS(ISET)=NUMIS(ISET)+COUNT(I)
      IF(COUNT(I).EQ.0) MISS(ISET)=MISS(ISET)+1
    4 CONTINUE
    6 CONTINUE
      WRITE(2,'(I3,A1,I3,9(A1,I3,A1,I3))')
     *NUMIS(1),HTAB,MISS(1),(HTAB,NUMIS(I),HTAB,MISS(I),I=2,10)
    8 CONTINUE
      END
