      PROGRAM SIZETEST
      PARAMETER (MAXCLONE=12500)
      CHARACTER*80 INFILE,OUTFILE
      CHARACTER*20 CH20,HEADER
      CHARACTER*5 CH5
      CHARACTER*1 CH1,HTAB,BLNK
      REAL*8 CLONE(MAXCLONE),SEED,VIN,TOTIS
      REAL VAR(MAXCLONE)
      INTEGER COUNT(100)
      DATA BLNK/' '/
C
      CALL GETARG(1,INFILE)
      CALL GETARG(2,OUTFILE)
      CALL GETARG(3,CH20)
      CALL GETARG(4,CH5)
      READ(CH20,*) SEED
      READ(CH5,*) NSAMP
      HTAB=CHAR(9)
      LENGTH=MAXCLONE
C
      OPEN(UNIT=1,FILE=INFILE,FORM='FORMATTED')
      REWIND(1)
      READ(1,'(A)') HEADER
      NCLONE=0
    2 READ(1,*,ERR=4,END=4) VIN
      IF(VIN.GT.0.0D0) THEN
        NCLONE=NCLONE+1
        CLONE(NCLONE)=VIN
        GOTO 2
      ENDIF
    4 CLOSE(1)
C..CALCULATE THE TOTAL NUMBER OF IS
      TOTIS=CLONE(1)
      DO 6 I=1,NCLONE
      TOTIS=TOTIS+CLONE(I)
    6 CONTINUE
C
C..RUN THE SIMULATION
C
      OPEN(UNIT=2,FILE=OUTFILE,FORM='FORMATTED')
      REWIND(2)
      IJ=INDEX(INFILE,BLNK)-1
      WRITE(2,'(2A)') 'Examination of ',INFILE(1:IJ)
      WRITE(2,'(A,I5)') 'Sample size for each trial is ',NSAMP
      WRITE(2,'(A,F12.0)') 'SEED = ',SEED
      WRITE(2,'(/A8,8(A1,A7,I1),90(A1,A6,I2),A1,A8)')
     *'Clone001',(HTAB,'Clone00',I,I=2,9),(HTAB,'Clone0',J,J=10,99),
     *HTAB,'Clone100'
C
      DO 14 ICYC=1,10000
      DO 8 I=1,100
      COUNT(I)=0
    8 CONTINUE
      CALL SURAND(SEED,LENGTH,VAR)
      DO 12 ISAMP=1,NSAMP
      VIN=VAR(ISAMP)
      VIN=VIN*TOTIS
      DO 10 I=1,100
      IF(CLONE(I).GT.VIN) THEN
        COUNT(I)=COUNT(I)+1
        GOTO 12
      ELSE
        VIN=VIN-CLONE(I)
      ENDIF
   10 CONTINUE
   12 CONTINUE
      WRITE(2,'(I5,99(A1,I5))') COUNT(1),(HTAB,COUNT(I),I=2,100)
   14 CONTINUE
      CLOSE(2)
      END
      SUBROUTINE SURAND(SEED,N,X)
      REAL*8 SEED,A,XM,XMI,ONE
      DIMENSION X(*)
      DATA A,XM,ONE/16807.0D0,2147483647.0D0,1.0D0/
      IF(N.LT.1) RETURN
      XMI=ONE/XM
      DO 10 I=1,N
      SEED=A*SEED
      IX=INT(SEED*XMI)
      SEED=SEED-FLOAT(IX)*XM
      X(I)=SEED*XMI
   10 CONTINUE
      RETURN
      END
