      PROGRAM TCRCOMP3
      PARAMETER (MAXSITE=60000,MAXTIME=5)
      CHARACTER*300 LINE,BL300
      CHARACTER*80 INFILE1,OUTFILE,PREFIX
      CHARACTER*30 P3L(MAXSITE),USEL(MAXSITE),BL30,CH30
      CHARACTER*20 HEADER(MAXTIME),BL20,CH20
      CHARACTER*10 CH10A,CH10B,BL10
      CHARACTER*3 CH3A,CH3B,CH3C
      CHARACTER*1 BLNK,HTAB,CH1
      INTEGER HAVE(MAXSITE),IHT(10),ICIN(10),LHEAD(MAXTIME)
      REAL COUNT(100,2),USE(MAXSITE,2),WGHT(MAXSITE),WGHT0(MAXSITE),
     *AX(5),BX(5),YCA(5),VAR(2020),DRELE(5),ROULET(100,MAXTIME)
      REAL*8 SEED,COUNTIN(MAXSITE,MAXTIME),TOTAL(MAXTIME),
     *RCLONE(MAXSITE),TCOUNT(MAXSITE),TOTTOT
      DATA BL300/' '/
      DATA BL10/'          '/
      DATA BL20/'                    '/
      DATA BL30/'                              '/
      DATA BLNK/' '/
C..This program uses a master roulette wheel selection procedure to select
C....100 clones and then other roulette wheels to choose 2000
C....insertion sites from these 100 clones, and calculates
C....their differences. This is repeated 10000 times.
      CALL GETARG(1,INFILE1)
      CALL GETARG(2,PREFIX)
      CALL GETARG(3,CH1)
      CALL GETARG(4,CH20)
      READ(CH1,'(I1)') NCOL
      IF(NCOL.GT.MAXTIME) THEN
        WRITE(*,'(A)') 'ERROR...NEED TO INCREASE MAXTIME'
        STOP
      ENDIF
      READ(CH20,*) SEED
      NPICK=100
      HTAB=CHAR(9)
      LENGTH=2020
C..READ INFILE1
      OPEN(UNIT=1,FILE=INFILE1,FORM='FORMATTED')
      REWIND(1)
      READ(1,'(A)') LINE
      IHT(1)=0
      DO 1 I=1,NCOL
      IHT(I+1)=INDEX(LINE,HTAB)
      LINE(IHT(I+1):IHT(I+1))=BLNK
    1 CONTINUE
      DO 101 I=1,NCOL
      HEADER(I)=BL10
      LHEAD(I)=IHT(I+1)-IHT(I)-1
      HEADER(I)(1:LHEAD(I))=LINE(IHT(I)+1:IHT(I+1)-1)
  101 CONTINUE
      NTCLONE=0
  102 READ(1,'(A)',ERR=103,END=103) LINE
      IJ=INDEX(LINE,HTAB)
      IF(IJ.LT.1) GOTO 103
      NTCLONE=NTCLONE+1
      IF(NTCLONE.GT.MAXSITE) THEN
        WRITE(*,'(A)') 'INCREASE MAXSITE'
        WRITE(*,'(A)') INFILE1
        STOP
      ENDIF
      READ(LINE,*)(COUNTIN(NTCLONE,J),J=1,NCOL)
      GOTO 102
  103 CONTINUE
      CLOSE(1)
C      WRITE(*,'(A,I8)') 'NTCLONE = ',NTCLONE
C..BUILD A SINGLE ROULETTE WHEEL (RCLONE(MAXSITE)) BASED ON THE TOTAL
C....COUNTS (TCOUNT(MAXSITE))
      TOTTOT=0.0D0
      DO 153 I=1,NTCLONE
      TCOUNT(I)=COUNTIN(I,1)
      DO 151 J=2,NCOL
      TCOUNT(I)=TCOUNT(I)+COUNTIN(I,J)
  151 CONTINUE
      TOTTOT=TOTTOT+TCOUNT(I)
  153 CONTINUE
C      WRITE(*,'(A,1PE12.5)') 'TOTTOT = ',TOTTOT
      TOTTOT=1.0D0/TOTTOT
      RCLONE(1)=TCOUNT(1)*TOTTOT
      DO 155 I=2,NTCLONE
      RCLONE(I)=RCLONE(I-1)+TCOUNT(I)*TOTTOT
  155 CONTINUE
      RCLONE(NTCLONE)=1.0D0
C      WRITE(*,'(8(1X,1PE12.5))')(RCLONE(I),I=1,8)
C
C..EXAMINE THE GROUPS ONE AT A TIME AND PAIRWISE
C
      LUKE=ICHAR('A')-1
      DO 148 JC=1,NCOL
      DO 146 IC=JC,NCOL
C
      LPRE=INDEX(PREFIX,BLNK)
      OUTFILE=PREFIX
      LUKE=LUKE+1
      OUTFILE(LPRE:LPRE)=CHAR(LUKE)
      OUTFILE(LPRE+1:LPRE+4)='.txt'
      OPEN(UNIT=2,FILE=OUTFILE,FORM='FORMATTED')
      REWIND(2)
      IJ=INDEX(INFILE1,BLNK)-1
      WRITE(2,'(6A)') 'Comparing ',HEADER(JC)(1:LHEAD(JC)),
     *' versus ',HEADER(IC)(1:LHEAD(IC)),
     *' from ',INFILE1(1:IJ)
      WRITE(2,'(A,I3,A)') 'Selecting top ',NPICK,' clones from each.'
      WRITE(2,'(A,F12.0)') 'SEED = ',SEED
      WRITE(2,'(/A3,4(A1,F3.1))') '0.0',(HTAB,0.5*FLOAT(I),I=1,4)
C
C..START RUNNING THE SIMULATIONS
C
      DO 44 IPERM=1,10000
C..SELECT THE 100 CLONES, FROM NTCLONE, BASED ON RCLONE(NTCLONE)
  199 DO 201 I=1,NTCLONE
      HAVE(I)=0
  201 CONTINUE
      CALL SURAND(SEED,LENGTH,VAR)
      LL=0
      DO 207 LBT=1,100
  203 LL=LL+1
      DO 205 I=1,NTCLONE
      IF(RCLONE(I).GE.VAR(LL)) THEN
        IF(HAVE(I).EQ.1) GOTO 203
        USE(LBT,1)=COUNTIN(I,JC)
        USE(LBT,2)=COUNTIN(I,IC)
        HAVE(I)=1
        GOTO 207
      ENDIF
  205 CONTINUE
  207 CONTINUE
C
C..BUILD THE TWO ROULETTE WHEELS BASED ON USE(100,2)
C
      DO 213 J=1,2
      TOTAL(J)=USE(1,J)
      DO 209 LBT=2,100
      TOTAL(J)=TOTAL(J)+USE(LBT,J)
  209 CONTINUE
      TOTAL(J)=1.0D0/TOTAL(J)
      ROULET(1,J)=USE(1,J)*TOTAL(J)
      DO 211 LBT=2,100
      ROULET(LBT,J)=ROULET(LBT-1,J)+TOTAL(J)*USE(LBT,J)
  211 CONTINUE
      ROULET(100,J)=1.0D0
  213 CONTINUE
C
      DO 14 J=1,2
      DO 12 I=1,100
      COUNT(I,J)=0.0
   12 CONTINUE
   14 CONTINUE
      DO 16 I=1,100
      HAVE(I)=0
   16 CONTINUE
C..FILL IN COUNT(I,1)
      CALL SURAND(SEED,LENGTH,VAR)
      DO 113 I=1,2000
      DO 111 K=1,100
      IF(ROULET(K,1).GE.VAR(I)) THEN
        COUNT(K,1)=COUNT(K,1)+1
        GOTO 113
      ENDIF
  111 CONTINUE
      WRITE(*,'(A)') 'Problem with COUNT(I,1)'
      WRITE(*,'(10F8.5)')(ROULET(K,1),K=1,100)
      WRITE(*,'(/F8.5)') VAR(I)
      COUNT(100,1)=COUNT(100,1)+1
  113 CONTINUE
C..FILL IN COUNT(I,2)
      CALL SURAND(SEED,LENGTH,VAR)
      DO 117 I=1,2000
      DO 115 K=1,100
      IF(ROULET(K,2).GE.VAR(I)) THEN
        COUNT(K,2)=COUNT(K,2)+1
        GOTO 117
      ENDIF
  115 CONTINUE
      WRITE(*,'(A)') 'Problem with COUNT(I,2)'
      WRITE(*,'(10F8.5)')(ROULET(K,2),K=1,100)
      WRITE(*,'(/F8.5)') VAR(I)
      COUNT(100,2)=COUNT(100,2)+1
  117 CONTINUE
C..SELECT THE NPICK CLONES FOR COMPARISON
      DO 24 IP=1,NPICK
      CM=-1.0
      IM=0
      DO 22 I=1,100
      IF(COUNT(I,1).GT.CM.AND.HAVE(I).EQ.0) THEN
        CM=COUNT(I,1)
        IM=I
      ENDIF
   22 CONTINUE
      USE(IP,1)=COUNT(IM,1)
      USE(IP,2)=COUNT(IM,2)
      HAVE(IM)=1
      IF(IP.EQ.NPICK) CL=COUNT(IM,1)
   24 CONTINUE
      NUSE=NPICK
C..LOOK FOR TIES NOT INCLUDED SO FAR
      DO 26 I=1,100
      IF(HAVE(I).EQ.0.AND.COUNT(I,1).EQ.CL) THEN
        NUSE=NUSE+1
        USEL(NUSE)=P3L(I)
        USE(NUSE,1)=COUNT(I,1)
        USE(NUSE,2)=COUNT(I,2)
        HAVE(I)=1
      ENDIF
   26 CONTINUE
C..LOOK FOR LARGEST CLONES FROM INFILE2
      DO 30 IP=1,NPICK
      CM=-1.0
      IM=0
      DO 28 I=1,100
      IF(HAVE(I).NE.2.AND.COUNT(I,2).GT.CM) THEN
        CM=COUNT(I,2)
        IM=I
      ENDIF
   28 CONTINUE
      IF(HAVE(IM).EQ.0) THEN
        NUSE=NUSE+1
C        USEL(NUSE)=P3L(IM)
        USE(NUSE,1)=COUNT(IM,1)
        USE(NUSE,2)=COUNT(IM,2)
      ENDIF
      HAVE(IM)=2
      IF(IP.EQ.NPICK) CL=COUNT(IM,2)
   30 CONTINUE
C..LOOK FOR TIES WITH CL
      NA2=0
      DO 32 I=1,100
      IF(HAVE(I).NE.2.AND.COUNT(I,2).EQ.CL) THEN
        NA2=NA2+1
        IF(HAVE(I).EQ.0) THEN
          NUSE=NUSE+1
C          USEL(NUSE)=P3L(I)
          USE(NUSE,1)=COUNT(I,1)
          USE(NUSE,2)=COUNT(I,2)
        ENDIF
        HAVE(I)=2
      ENDIF
   32 CONTINUE
C..BUILD WGHT0(NUSE)
C..FIRST SCALE ALL DATA SO THAT THE AVERAGE OF EACH SET IS 20.0
      DO 133 I=1,NUSE
      WGHT0(I)=0.5*(USE(I,1)+USE(I,2))
      IF(WGHT0(I).EQ.0.0) WGHT0(I)=1.0
  133 CONTINUE
C..START THE NONLINEAR FITS
      DO 42 IZ=1,5
      Z=0.5*FLOAT(IZ-1)
      DO 36 I=1,NUSE
      WGHT(I)=WGHT0(I)**Z
   36 CONTINUE
      W=0.0
      WX=0.0
      WY=0.0
      WXX=0.0
      WXY=0.0
      DO 38 I=1,NUSE
      W=W+WGHT(I)
      WX=WX+WGHT(I)*USE(I,1)
      WY=WY+WGHT(I)*USE(I,2)
      WXX=WXX+WGHT(I)*USE(I,1)*USE(I,1)
      WXY=WXY+WGHT(I)*USE(I,1)*USE(I,2)
   38 CONTINUE
      ZZZ=WX*WX-W*WXX
      IF(ZZZ.EQ.0.0) GOTO 199
      B=(WX*WY-W*WXY)/ZZZ
      IF(W.EQ.0.0) GOTO 199
      A=(WY-B*WX)/W
      AX(IZ)=A
      BX(IZ)=B
      RMSE=0.0
      AAE=0.0
      RELE=0.0
      IF(B.EQ.0.0) GOTO 199
      DEN=1.0/(B+(1.0/B))
      DO 40 I=1,NUSE
      XDP=(USE(I,2)+(USE(I,1)/B)-A)*DEN
      YDP=B*XDP+A
      DIS=SQRT((XDP-USE(I,1))**2+(YDP-USE(I,2))**2)
      RMSE=RMSE+DIS**2
      AAE=AAE+DIS
      RELE=RELE+DIS**2/WGHT0(I)
   40 CONTINUE
      RMSE=SQRT(RMSE/FLOAT(NUSE))
      AAE=AAE/FLOAT(NUSE)
      RELE=RELE/FLOAT(NUSE)
      DRELE(IZ)=RELE
   42 CONTINUE
      WRITE(2,'(F10.5,4(A1,F10.4))') DRELE(1),(HTAB,DRELE(I),I=2,5)
C..DONE WITH A PERMUTATION
   44 CONTINUE
      CLOSE(2)
  146 CONTINUE
  148 CONTINUE
      END
      SUBROUTINE SURAND(SEED,N,X)
      REAL*8 SEED,A,XM,XMI,ONE
      DIMENSION X(*)
      DATA A,XM,ONE/16807.0D0,2147483647.0D0,1.0D0/
      IF(N.LT.1) RETURN
      XMI=ONE/XM
      DO 10 I=1,N
      SEED=A*SEED
      IX=INT(SEED*XMI)
      SEED=SEED-FLOAT(IX)*XM
      X(I)=SEED*XMI
   10 CONTINUE
      RETURN
      END
